apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM1RENDQWN5Z0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFqTVJBd0RnWURWUVFLRXdkck0zTXQKYjNKbk1ROHdEUVlEVlFRREV3WnJNM010WTJFd0hoY05NVGt3TnpBeE1qTXlPREl5V2hjTk1qa3dOakk0TWpNeQpPREl5V2pBak1SQXdEZ1lEVlFRS0V3ZHJNM010YjNKbk1ROHdEUVlEVlFRREV3WnJNM010WTJFd2dnRWlNQTBHCkNTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFEWGpQcTErcHVOTVIyOXFOU2tiSU11Q05CVnl5NzgKeUtJbzk1NW1OUFNWK1J4V3E0UUZRYUhIdTRPa0FoUm9DQU1ISGNOM2pMQ0NYdGNYREVFYmxCUkVNYjhqTDJrKwpjTDJIRk1GM1Z4U0RPTW1KNTV3MjNqamhGeDA2cVBjQ2FDWDhiMzZ5Z0NGVHI4YjJjb0QvSDNCSGpmMEJqTlV4CjVCK3hhZ0pwTGk2MlVwUXZLbG13K2p3RTRwNElyb0NPemx6dVRMTGxFOXl6UW1jRmFaSWN3WFZZdFgvTWRiUlIKbXVLdXZBWmtpbmRjcmhLZHVlRWFyU2VSSUlSbEQ4eCtYU3hyUFVhSFhHSXpvM3RDbkVlQmpoNTVzQW9Gc3pNVApTZnlNa20zRTVnUG84MG1IQllnTUY5ZHFlUEJ4ZllYczl4Q283RGQxNTRQd2krWDZjdndsdUg4TkFnTUJBQUdqCkl6QWhNQTRHQTFVZER3RUIvd1FFQXdJQ3BEQVBCZ05WSFJNQkFmOEVCVEFEQVFIL01BMEdDU3FHU0liM0RRRUIKQ3dVQUE0SUJBUUNLWmF1TW83VGxrQi9LcldsR3dkUmJjcWRzQmcyYzJBWXdaeWhFZHNhWnNCaWxOcnMwZTVjNgpVMFY1TTIrRldxR3M1d0pzcHBPVWwzaWhqYkhGWHY4MkdPL0R1R210eXhBS1Nvc2grUjk3eis4QnVhWEdSK3VQCnJmZTl6MXY2L2NxcUcrYkc0dzZub0VZVzVOa1ErOXpJRDhTZi9BQTRKSHdZQ0g3N1JIRU9pazVvSG14WGZMNm0KRDZ6Q1FYeHNpQWhsUGJ1T1ViVmtQNG10M3NNNmllVmdwcGVSdlFpL1p2M0FSUi8vU21Ib1NLS2VocnRGcG45eAo4cjhYQlFVWUhlNWFLV256YUxhdlVHSnlCUXdqVk5sdXdSOFpBYmEzcEhqUHROam1CTzZtK0JWa1lNMlRUQkxKCjdYU2NIZURwNmIrTGFZWituWklNcnpxdGtyQzZtdlpHCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://192.168.0.87:6443
  name: default
contexts:
- context:
    cluster: default
    user: default
  name: default
current-context: default
kind: Config
preferences: {}
users:
- name: default
  user:
    password: 6f34e9afbeb9790fc105657f438ef29a
    username: admin
