k3s_version: v1.19.4+k3s1
ansible_user: odroid
ansible_become_password: odroid
full_clean_install: True # BOOLEAN - Removes files from /var/lib/rancher/k3s
systemd_dir: /etc/systemd/system
master_ip: "{{ hostvars[groups['master'][0]]['ansible_host'] | default(groups['master'][0]) }}"
