---
- name: Ensure US locale exists
  locale_gen:
    name: en_US.UTF-8
    state: present
  
- name: Update apt cache and upgrade
  apt:
    update_cache: yes
    upgrade: "yes"
  async: 6400
  poll: 5

- name: Remove old packages and depencies.
  apt:
    autoclean: yes
    autoremove: yes
  async: 6400
  poll: 5

# - name: Activating cgroup on Raspbian
#   lineinfile:
#     path: /boot/cmdline.txt
#     regexp: '^(.*rootwait)$'
#     line: '\1 cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory'
#     backrefs: true
#   when: ( ansible_facts.architecture is search "arm" )

- name: Disable Swap
  shell: dphys-swapfile swapoff && dphys-swapfile uninstall && update-rc.d dphys-swapfile remove
  ignore_errors: True

- name: Set GPU memory split to 16 MB
  lineinfile:
    path: /boot/config.txt
    line: 'gpu_mem=16'
    create: yes
